export const AUTH_CODE_LIFETIME_MS = 60_000;
export const INTERACTION_LIFETIME_MS = 10 * 60 * 1000;
export const ACCESS_TOKEN_LIFETIME_MS = 60 * 60 * 1000;
export const ACCESS_TOKEN_LIFETIME_SECONDS = ACCESS_TOKEN_LIFETIME_MS / 1000;
export const REFRESH_TOKEN_LIFETIME_MS = 30 * 24 * 60 * 60 * 1000;

export const CLIENT_JWT_MAX_AGE_SECONDS = 60;
export const CLIENT_JWT_CLOCK_TOLERANCE_SECONDS = 30;

export const CLIENT_BACKCHANNEL_MAX_RETRIES = 10;
export const CLIENT_BACKCHANNEL_RETRY_INTERVAL_MS = 2 * 60 * 1000;
export const CLIENT_BACKCHANNEL_RETRY_LIFETIME_MS =
    CLIENT_BACKCHANNEL_RETRY_INTERVAL_MS * CLIENT_BACKCHANNEL_MAX_RETRIES +
    30 * 1000;

export const OAUTH_TOKEN_RATE_LIMIT_MAX = 50;
export const OAUTH_TOKEN_RATE_LIMIT_WINDOW_MINUTES = 15;
